export const RESET_TIMER = 'RESET_TIMER'
export const CHANGE_VALUE = 'CHANGE_VALUE'
export const START_TIMER = 'START_TIMER'
export const STOP_TIMER = 'STOP_TIMER'
export const RUN_TICKER = 'RUN_TICKER'
export const CLEAR_TIMER = 'CLEAR_TIMER'
export const START_BLINK_PAGE = 'START_BLINK_PAGE'
export const STOP_BLINK_PAGE = 'STOP_BLINK_PAGE'
