// textarea
export const SHOW_HOME = 'SHOW_HOME';
export const SET_MARKDOWN_TEXT = 'SET_MARKDOWN_TEXT';
export const EDIT_TEXTAREA_VALUE = 'EDIT_TEXTAREA_VALUE';

// header
export const SHOW_DEFAULT = 'SHOW_DEFAULT';
export const SET_FILE_NAME = 'SET_FILE_NAME';
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN';
export const SET_PLAY_SCREEN = 'SET_PLAY_SCREEN';

// pages
export const SPLIT_MARKDOWN_AS_PAGES = 'SPLIT_MARKDOWN_AS_PAGES';
export const UPDATE_PAGE_INDEX = 'UPDATE_PAGE_INDEX';
export const CLEAR_PAGES = 'CLEAR_PAGES';

// theme
export const SELECT_THEME = 'SELECT_THEME';

// codeStyle
export const SELECT_HIGHLIGHT_THEME = 'SELECT_HIGHLIGHT_THEME';

// aspectRatio
export const SELECT_RATIO = 'SELECT_RATIO';

// progressBar
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const SET_TOTAL_SECONDS = 'SET_TOTAL_SECONDS';
export const SET_INTERVAL_ID = 'SET_INTERVAL_ID';
export const UPDATE_ELAPSED_SECONDS = 'UPDATE_ELAPSED_SECONDS';
export const SET_ELAPSED_INTERVAL_ID = 'SET_ELAPSED_INTERVAL_ID';
export const STOP_ELAPSED_TIME_RUNNING = 'STOP_ELAPSED_TIME_RUNNING';
export const TOGGLE_ICONS = 'TOGGLE_ICONS';
