// home
export const SHOW_HOME = 'SHOW_HOME'
export const SET_MARKDOWN_TEXT = 'SET_MARKDOWN_TEXT'
export const EDIT_TEXTAREA_VALUE = 'EDIT_TEXTAREA_VALUE'

// header
export const SHOW_DEFAULT = 'SHOW_DEFAULT'
export const SET_FILE_NAME = 'SET_FILE_NAME'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

// pages
export const SPLIT_MARKDOWN_AS_PAGES = 'SPLIT_MARKDOWN_AS_PAGES'
export const UPDATE_PAGE_INDEX = 'UPDATE_PAGE_INDEX'
